---
- hosts: all

  tasks:
    - name: get current directory
      ansible.builtin.shell: pwd
      register: current_dir

    - name: print true when find vagrant
      debug:
        msg: "true if vagrant in current_dir"
      when: '"vagrant" in current_dir.stdout'
