---
- name: Install Nginx.
  hosts: nginx
  become: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Ensure apt cache is updated.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - geerlingguy.nginx

  tasks:
    - name: Copy Nginx server configuration in place.
      ansible.builtin.template:
        src: templates/{{ server_hostname }}.conf.j2
        dest: "/etc/nginx/sites-available/{{ server_hostname }}.conf"
        mode: 0644
        force: yes
      notify: restart nginx

    - name: Enable Nginx server configuration.
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ server_hostname }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ server_hostname }}.conf"
        state: link
