---
#####################
# 1. Chrony
#####################

# Time servers
chrony_config_server:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org


################################
# 2. Pushgateway Configuration
################################

# Pushgateway package version
pushgateway_version: latest
