---
- hosts: all
  become: yes

  tasks:
    # 默认更新所有，可以配置指定包，/etc/yum.conf；

    # RHEL and CentOS 6 and 7 (and older versions of Fedora),
    #       use packages + server: `yum-cron`;

    # RHEL and CentOS 8 and later (and latest versions of Fedora),
    #       use package: `dnf-automatic` and service: dnf-automatic-install.timer
    - name: Install yum-cron
      yum: name=yum-cron state=latest
      when: ansible_os_family == 'RedHat'

    - name: Ensure yum-cron is running and enabled on boot
      service: name=yum-cron state=started enabled=yes
      when: ansible_os_family == 'RedHat'

    # 配置 /etc/apt/apt.conf.d/；

    - name: Install unattended upgrades package.
      apt: name=unattended-upgrades state=present
      when: ansible_os_family == 'Debian'

    - name: Copy unattended-upgrades configuration files in place.
      template:
        src: "templates/auto_updates/{{ item }}.j2"
        dest: "/etc/apt/apt.conf.d/{{ item }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - 10periodic
        - 50unattended-upgrades
      when: ansible_os_family == 'Debian'