---
- hosts: all
  become: yes

  tasks:
    - name: Configure open ports with ufw.
      ufw:
        rule: "{{ item.rule }}"
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      with_items:
        - { rule: 'allow', port: 22, proto: 'tcp' }  # SSH
        - { rule: 'allow', port: 80, proto: 'tcp' }  # HTTP
        - { rule: 'allow', port: 123, proto: 'udp' } # NTP
      when: ansible_os_family == 'Debian'


    - name: Configure default incoming/outgoing rules with ufw
      ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
        state: enabled
      with_items:
        - { direction: outgoing, policy: allow }
        - { direction: incoming, policy: deny }
      when: ansible_os_family == 'Debian'

    # 查看结果： sudo ufw status verbose

    - name: Configure open ports with firewalld.
      firewalld:
        state: "{{ item.state }}"
        port: "{{ item.port }}"
        zone: external
        immediate: yes
        permanent: yes
      with_items:
        - { state: 'enabled', port: '22/tcp' }
        - { state: 'enabled', port: '80/tcp' }
        - { state: 'enabled', port: '123/udp' }
