---
- hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Calculate the timestamp of specific time.
      # TZ=Asia/Shanghai date -d "{{ pass_date_time }}" +%s
      shell: >-
        date -d "{{ pass_date_time }}" +%s
      register: timestamp
      vars:
        pass_date_time: "2024-04-01 14:00:00"          # TODO: 修改一个过去的时间

    - name: Find the target files.
      find:
        paths: /tmp
        # 1(s), 1m, 1h, 1d, 1w; 正数表示查找大于或等于这个年龄的文件；负数表示查找小于或等于这个年龄的文件；
        # age: 60
        # 当前时间 - 文件的出生时间 = 文件的年龄
        age: "{{ ansible_date_time.epoch | int - timestamp.stdout | int }}"
        age_stamp: mtime            # atime, mtime, ctime
        patterns: "*.txt"
        file_type: file             # directory, file, link
        # recurse: yes
      register: target_files


    - name: Remove files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ target_files.files }}"


