---
- hosts: all

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - include_tasks: setup-gitlab.yml
      when: ansible_os_family == "Debian"

