---
- hosts: lamp_www
  become: yes

  vars_files:
    - vars.yml

  roles:
    - buluma.selinux
    - geerlingguy.firewall
    - geerlingguy.repo-epel
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.php-memcached

  tasks:
    - name: Remove the Apache test page.
      file:
        path: /var/www/html/index.html
        state: absent
    - name: Copy our fancy server-specific home page.
      template:
        src: "templates/index.php.j2"
        dest: "/var/www/html/index.php"

