---
# 是否禁用防火墙
firewall_disable_firewalld: false  # RHEL/CentOS
firewall_disable_ufw: false        # Ubuntu

# 是否允许 ipv6 配置
firewall_enable_ipv6: true

# 启动防火墙，并设置开机启动
firewall_state: started
firewall_enabled_at_boot: true

# 设置重启防火墙时，是否刷新所有规则和链；如果存在其他进程在管理 iptables（e.g. Docker) 请关闭。
firewall_flush_rules_and_chains: true

# 对传入的流量，要开放的端口
firewall_allowed_tcp_ports:
  - "2849"
firewall_allowed_udp_ports: []

# 本地端口转发
firewall_forwarded_tcp_ports: []
  # - { src: "22", dest: "2222" }
  # - { src: "80", dest: "8080" }
firewall_forwarded_udp_ports: []

# 直接使用命令配置： iptables [rule]/ip6tables [rule]
firewall_additional_rules: []
  # Allow only the IP 167.89.89.18 to access port 4949 (Munin).
  # - "iptables -A INPUT -p tcp -s 167.89.89.18 --dport 4949  -j ACCEPT"

  # Allow only the IP 214.192.48.21 to access port 3306 (MySQL).
  # - "iptables -A INPUT -p tcp -s 214.192.48.21 --dport 3306 -j ACCEPT"
firewall_ip6_additional_rules: []


# 是否记录被丢弃的包，消息前缀：Dropped by firewall:
firewall_log_dropped_packets: false