---
- hosts: all
  become: yes

  tasks:
    - name: Add user node-exporter
      ansible.builtin.user:
        name: node-exporter
        state: present
        createhome: false
        shell: /bin/false

    - ansible.builtin.stat:
        path: /usr/local/bin/node_exporter
      register: node_exporter_archive
    - name: upload "files/node_exporter"
      ansible.builtin.copy:
        src: files/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: '0744'
        owner: node-exporter
        group: node-exporter
      when: node_exporter_archive.stat.exists == false

    - ansible.builtin.stat:
        path: /etc/systemd/system/node_exporter.service
      register: node_exporter_service_archive
    - name: upload "files/node_exporter.service"
      ansible.builtin.copy:
        src: "files/node_exporter.service"
        dest: /etc/systemd/system/node_exporter.service
      when: node_exporter_service_archive.stat.exists == false

    - name: Start service
      ansible.builtin.systemd_service:
        name: node_exporter
        state: started
        enabled: true
        daemon_reload: true

    - name: debug
      ansible.builtin.debug:
        msg: "http://{{ ansible_enp0s8.ipv4.address }}:9100/metrics"


