---
- hosts: all
  become: yes

  tasks:
    - name: Install EPEL repo.
      tags:
        - epel
      package: name=epel-release state=present

    - name: Import Remi GPG key.
      tags:
        - remi
      ansible.builtin.rpm_key:
        key: https://rpms.remirepo.net/RPM-GPG-KEY-remi
        state: present

    - name: Install Remi repo.
      tags:
        - remi
      ansible.builtin.package:
        name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present



