---
- hosts: all
  become: yes

  tasks:
    - name: Download a file, using example-proxy as a proxy.
      get_url: url=http://www.example.com/file.tar.gz dest=~/Downloads/
      environment:
        http_proxy: http://clash.proxy.com:7890

