---
- name: Ensure dependencies are installed.
  apt:
    name:
      - curl
      - ca-certificates

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Check if key exists
  stat:
    path: /etc/apt/keyrings/docker.asc
  register: key_file

- name: Add Docker apt repository key.
  get_url:
    url: "{{ docker_repo_key_url }}"
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644
    timeout: 30
    force: no
  retries: 5
  delay: 10
  register: download_result
  until: download_result is succeeded
  when: not key_file.stat.exists

- name: Add Docker apt repository.
  apt_repository:
    repo: "{{ docker_repo_url }}"
    state: present
    update_cache: true
    filename: "docker"
  when: docker_repo_url | default(false)

- name: Install Docker packages.
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Configure docker
  template:
    src: "templates/daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    mode: 0644
  notify: Restart docker