Vagrant.configure("2") do |config|
  config.vm.box = "vladimir-babichev/openwrt-22.03"

  config.vm.hostname = "openwrt"

  config.vm.synced_folder ".", "/root", disabled: true

  config.vm.provider "virtualbox" do |v|
    v.memory = "512"
    v.cpus = "2"

    v.customize ["modifyvm", :id, "--nic2", "bridged", "--bridgeadapter2", "enp6s0"]
    v.customize ["modifyvm", :id, "--nic3", "bridged", "--bridgeadapter3", "enp6s0"]
  end

#   config.vm.network "private_network", ip: "192.168.56.2"

  config.vm.provision "shell", inline: <<-SHELL
    opkg remove dnsmasq wpad-mini
    opkg update
    opkg install wpad rsync sudo coreutils-nohup bash iptables dnsmasq-full curl ca-certificates ipset ip-full \
            iptables-mod-tproxy iptables-mod-extra libcap libcap-bin ruby ruby-yaml kmod-tun kmod-inet-diag unzip \
                luci-compat luci luci-base luci-theme-material luci-i18n-base-zh-cn luci-i18n-opkg-zh-cn \
                    luci-i18n-firewall-zh-cn luci-i18n-dnscrypt-proxy-zh-cn luci-i18n-simple-adblock-zh-cn \
			luci-i18n-nlbwmon-zh-cn ca-bundle 
  SHELL

end
