---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.git
    - geerlingguy.nodejs
    - geerlingguy.ruby
    - geerlingguy.passenger

  tasks:
    - name: Install app dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - libsqlite3-dev
        - libreadline-dev
        - tzdata

    - name: Ensure app directory exists and is writable
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: 0775