---
- name: Deploy and manage Prometheus alertmanager service using ansible.
  hosts: alertmanager
  become: true

  vars_files:
    - vars/alertmanager/main.yml

  roles:
    - role: cloudalchemy.alertmanager
