---
- name: Deploy prometheus node exporter
  hosts: node_exporter
  become: true

  vars_files:
    - vars/node_exporter/main.yml

  roles:
    - role: ericsysmin.chrony
    - role: cloudalchemy.node_exporter


