---
- name: Deploy Prometheus monitoring system
  hosts: prometheus
  become: true

  vars_files:
    - vars/prometheus/main.yml

  roles:
    - role: ericsysmin.chrony
    - role: cloudalchemy.prometheus
