# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.hostname = "jenkinsci.test"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.insert_key = false

  # config.vm.network :private_network, ip: "192.168.137.20"
  config.vm.network "public_network", ip: "192.168.137.20", bridge: "enp6s0"

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  # Ansible provisioning.
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"

    ansible.playbook = "provision.yml"
    ansible.become = true
  end
end



