# # -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = "common"
    v.memory = 512
    v.cpus = 1
  end

  # Rails server.
  config.vm.hostname = "common"
  config.vm.network :private_network, ip: "192.168.10.5"

end



