---
#
# defaults file for anaconda
#
# The version of python to install, either 2 or 3.
anaconda_python_version: 3

# The version of anaconda to install.
# See https://www.anaconda.com/distribution/
# See https://repo.anaconda.com/archive/
anaconda_version: "2022.10"
# anaconda_version: "2024.02-1"

# What ip and port to let anaconda listen to.
anaconda_ip: "0.0.0.0"
anaconda_port: 8888

# Where to save the (large) download file
anaconda_download_dest: /tmp

# Where to install anaconda
anaconda_prefix: /root/anaconda3
# anaconda_prefix: /opt/anaconda3

#
# GPT Academic
#
app_name: "gpt_academic"
app_version: "version3.74"
app_directory: /opt/gpt_academic
app_user: vagrant
