---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
    - import_tasks: user.yml
      vars:
        username: johndoe
        ssh_private_keys:
          - src: id_rsa
            dest: id_rsa
          - src: id_rsa.pub
            dest: id_rsa.pub
