---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
    - ansible.builtin.import_tasks:
        name: "{{ item }}"
      with_items:
        - tasks/1.yml
        - tasks/2.yml
        - tasks/3.yml
        - tasks/4.yml
        - tasks/5.yml
        - tasks/6.yml
        - tasks/7.yml
        - tasks/8.yml
        - tasks/9.yml
        - tasks/10.yml
        - tasks/11.yml
        - tasks/12.yml
        - tasks/13.yml
        - tasks/14.yml
        - tasks/15.yml
        - tasks/16.yml
        - tasks/17.yml
        - tasks/18.yml
        - tasks/19.yml
        - tasks/20.yml
        - tasks/21.yml
        - tasks/22.yml
        - tasks/23.yml
        - tasks/24.yml
        - tasks/25.yml
        - tasks/26.yml
        - tasks/27.yml
        - tasks/28.yml
        - tasks/29.yml
        - tasks/30.yml
        - tasks/31.yml
        - tasks/32.yml
        - tasks/33.yml
        - tasks/34.yml
        - tasks/35.yml
        - tasks/36.yml
        - tasks/37.yml
        - tasks/38.yml
        - tasks/39.yml
        - tasks/40.yml
        - tasks/41.yml
        - tasks/42.yml
        - tasks/43.yml
        - tasks/44.yml
        - tasks/45.yml
        - tasks/46.yml
        - tasks/47.yml
        - tasks/48.yml
        - tasks/49.yml
        - tasks/50.yml
        - tasks/51.yml
        - tasks/52.yml
        - tasks/53.yml
        - tasks/54.yml
        - tasks/55.yml
        - tasks/56.yml
        - tasks/57.yml
        - tasks/58.yml
        - tasks/59.yml
        - tasks/60.yml
        - tasks/61.yml
        - tasks/62.yml
        - tasks/63.yml
        - tasks/64.yml
        - tasks/65.yml
        - tasks/66.yml
        - tasks/67.yml
        - tasks/68.yml
        - tasks/69.yml
        - tasks/70.yml