- hosts: all
  gather_facts: no

  tasks:
    - name: Wait for web server to start
      local_action:
        module: wait_for
        host: "{{ inventory_hostname }}"
        port: "{{ webserver_port }}"
        delay: 10
        timeout: 300
        state: started