---
- hosts: all

  # vars_files:
  #   - vars.yml

  vars:
    foo: bar_in_vars_section

  tasks:
    # Prints "Variable 'foo' is set to bar".
    - debug: msg="Variable 'foo' is set to {{ foo }}"

    - debug:
        var: ansible_os_family