---

- name: Check list of running Node.js apps.
  command: /usr/local/bin/forever list
  register: forever_list
  changed_when: false

# - name: Debug forever_list
#   ansible.builtin.debug:
#     var: forever_list

- name: Start example Node.js app.
  ansible.builtin.command: /usr/local/bin/forever start {{ node_apps_location }}/app/app.js
  when: forever_list.stdout.find(node_apps_location + "/app/app.js") == -1

