---
- hosts: all

  tasks:
    - name: "Node: Check list of Node.js apps running."
      command: >
        ls
        -l
        -a
      register: ls_list
      changed_when: false

    - name: "Node: Start example Node.js app."
      debug:
        var: ls_list.stdout.find("bash")