---
- hosts: all
  # gather_facts: no
  become: yes

  tasks:
    - name: Reload local file
      setup: filter=ansible_local
      register: ansible_local

    - debug:
        var: ansible_local.ansible_facts.ansible_local.settings.users