---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Test connection
      ansible.builtin.ping:

- import_playbook: web.yml
- ansible.builtin.import_playbook:
    src: db.yml
    vars:
      db_name: myapp_production
      other_variable: some_value
  tags:
    - db