---
groups:
  - name: example
    rules:
    - alert: InstanceDown
      expr: up{job="node"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.{% endraw %}"
        summary: "{% raw %}Instance {{ $labels.instance }} down{% endraw %}"
