# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.hostname = "GPT-Academic.lab.percxh.com"
  config.ssh.insert_key = false


  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end

  config.vm.network :private_network, ip: "192.168.10.10"

  # Ansible provisioning.
  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "provision.yml"
  #   ansible.become = true
  # end
end



